import { createContext } from "#graphql/context";
import { defineEventHandler, sendWebResponse, toWebRequest } from "h3";

import { getYogaInstance } from "../lib/yoga";

/**
 * Handle GraphQL HTTP requests using Yoga.
 *
 * @param event H3 request event.
 * @returns Web response generated by Yoga.
 */
export default defineEventHandler(async (event) => {
  const yoga = getYogaInstance();
  const request = toWebRequest(event);
  const context = await createContext(event);
  const response = await yoga.handleRequest(request, context);
  return sendWebResponse(event, response);
});
